- hosts: all
  tasks:
    - name: Install ruby
      yum:
        name: ruby
        state: present

    - name: Install sinatra
      yum:
        name: sinatra
        version: 1.4.8

    - name: Create service template
      become: yes
      template:
        src: web.rb.service.j2
        dest: /etc/systemd/system/ruby.service

    - name: Create a directory if it does not exist
      file:
        path: "{{home_folder}}/deployment"
        state: directory
        mode: '0755'

    - name: Remove file
      file:
        path: "{{home_folder}}/deployment/web.rb"
        state: absent

    - name: copy artifact
      copy:
        src: web.rb
        backup: yes
        force: yes
        dest: "{{home_folder}}/deployment/web.rb"
        mode: '0777'
    
    - name: enable and start service
      become: yes
      systemd:
        name: web.rb
        enabled: yes
        state: restarted
